### ISSUE TITLE
Lua in ingress-nginx

### ISSUE THREAD

**Issue by wkloucek** [ONLYOFFICE/Kubernetes-Docs-Shards#13]
I saw that you're making use of lua plugins in:

https://github.com/ONLYOFFICE/Kubernetes-Docs-Shards/blob/0297dcbbacec1f17185dd80bdf2efa12d68e5ab8/sources/ingress_values.yaml#L7-L9

According to https://github.com/kubernetes/ingress-nginx/issues/10186 / https://github.com/kubernetes/ingress-nginx/pull/11821 third party support for Lua plugins is gonna be removed from ingress-nginx.

Does affect this chart and how can it be mitigated? Maybe use a standalone nginx and not a ingress-nginx based nginx?

**Comment by alexanderonlyoffice** [comment]
Hello @wkloucek, mentioned PRs are disabling the plugins, but we are just mounting the slightly refined [balancer](https://github.com/ONLYOFFICE/Kubernetes-Docs-Shards/blob/master/templates/configmaps/balancer-lua.yaml#L369C8-L371C12), so that it reverts back the endpoint which we actually use afterwards in our load balancing. These changes in the controller will not affect our chart functioning.

**Comment by wkloucek** [comment]
> but we are just mounting the slightly refined [balancer](https://github.com/ONLYOFFICE/Kubernetes-Docs-Shards/blob/master/templates/configmaps/balancer-lua.yaml#L369C8-L371C12),

OK, that looks like it's gonna continue to work.

But actually because of this mechanism I see problems that we can actually use this setup.
We have a ingress controller already on our clusters that we must not change that invasive for the OnlyOffice installation, since it's also used for other applications.

Would it be possible to maybe have a "regular" nginx as a Deployment which receives the traffic from the "untouched" ingress controller (which could be nginx-ingress, HA proxy, ...)

For example Grafana Mimir also ships a NGINX deployment for similar funcitonality like you have it for OnlyOffice, see https://github.com/grafana/mimir/tree/main/operations/helm/charts/mimir-distributed/templates/gateway

**Comment by alexanderonlyoffice** [comment]
@wkloucek, 

> "We have a ingress controller already on our clusters that we must not change that invasive for the OnlyOffice installation, since it's also used for other applications."

Please specify if you have already looked through this [section](https://github.com/ONLYOFFICE/Kubernetes-Docs-Shards/tree/master?tab=readme-ov-file#111-use-your-own-nginx-ingress-controller) of the article where the usage of already set nginx-ingress controller is mentioned. Please let me know what you think about it. 

> "Would it be possible to maybe have a "regular" nginx as a Deployment which receives the traffic from the "untouched" ingress controller (which could be nginx-ingress, HA proxy, ...)"

Our Nginx Ingress Controller based load balancing uses the built-in mechanism for obtaining DS replica endpoints and our lua proxy script based on a request argument. We require to consider and implement such a mechanism when we are talking about "regular" nginx. 

@rikatz, 

> "sorry for be intrusive, but I would love to know how kubernetes/ingress-nginx#11819 will impact you folks :)"

We checked the deployment with enabled `controller.enableAnnotationValidations` and this parameter did not affect chart functioning. Do you have a test build with the changes added by this PR somewhere, we would like to do more testing? 

> "Can you please provide some feedback on some features we are marking to deprecate as well?"

Unfortunately, we saw only few of them, do you have a list of the features you are going to mark to deprecate in the future releases, so to say "a to-do" list?

**Comment by rikatz** [comment]
https://github.com/kubernetes/ingress-nginx/issues/10186

**Comment by alexanderonlyoffice** [comment]
@rikatz, thanks for pointing it out for us again, we can confirm that the changes to be added in the next release will not affect our chart. We will track the future changes as well to make sure everything will works from our end.

**Comment by wkloucek** [comment]
> Please specify if you have already looked through this [section](https://github.com/ONLYOFFICE/Kubernetes-Docs-Shards/tree/master?tab=readme-ov-file#111-use-your-own-nginx-ingress-controller) of the article where the usage of already set nginx-ingress controller is mentioned. Please let me know what you think about it.

Honestly I'd still prefer a more self contained solution like described in https://github.com/ONLYOFFICE/Kubernetes-Docs-Shards/issues/13#issuecomment-2296461326:

> Would it be possible to maybe have a "regular" nginx as a Deployment which receives the traffic from the "untouched" ingress controller (which could be nginx-ingress, HA proxy, ...)
> For example Grafana Mimir also ships a NGINX deployment for similar functionality like you have it for OnlyOffice, see https://github.com/grafana/mimir/tree/main/operations/helm/charts/mimir-distributed/templates/gateway

With the current solution, how can I deploy OnlyOffice on a cluster:
- where I don't manage the ingress controller, like in multi tenant clusters?
- where I don't have nginx-ingress as ingress controller? Eg. OpenShift has HAproxy by default
- where I want to deploy OnlyOffice multiple times in different namespaces?

**Comment by wkloucek** [comment]
The error handling in one of the lua scripts seems to be odd:

> onlyoffice-ingress-nginx-controller-6699bdfb96-wg5v8 controller 10.244.0.59 - - [11/Oct/2024:07:25:25 +0000] "GET /hosting/wopi/word/edit?WOPISrc=http%3A%2F%2Fcollaboration-onlyoffice.ocis.svc.cluster.local%3A9300%2Fwopi%2Ffiles%2F931b364de4ceb7f9a10ea954aa844b5495b8023e3d9da46c7e0c4fa4bee12edb&ui=en-US HTTP/2.0" 200 77 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36" 156 0.000 [onlyoffice-documentserver-8888] [] - - - - 510715c84391f0803375a185831ecec4

![image](https://github.com/user-attachments/assets/995a3149-6c4f-4312-a63e-8e4d20790862)


There shouldn't be any failure that is ONLY visible to end  users in the frontend without raising any error log in the backend.

**Comment by alexonlyoffice** [comment]
@wkloucek, please specify if you are deploying the solution from master branch. Let me also know what namespace Redis is deployed at, is it the default one? If you used another namespace for Redis deployment, please make sure you indicated it [here](https://github.com/ONLYOFFICE/Kubernetes-Docs-Shards/blob/master/values.yaml#L46) and changed service name for Redis. 

>  There shouldn't be any failure that is ONLY visible to end users in the frontend without raising any error log in the backend. 

we will add logging to the controller.

**Comment by wkloucek** [comment]
I was working on this deployment example: https://github.com/owncloud/ocis-charts/pull/765

I got it working after looking into the sharded chart. But actually since the lua configmaps have https://github.com/ONLYOFFICE/Kubernetes-Docs-Shards/blob/fe4a0a1b56394757b62983560415ddbce8658e1e/templates/configmaps/balancer-lua.yaml#L18, the config map is only created once. Therefore changes to the redis host, are not being applied. Which is somehow counter-intuitive to be honest...

**Comment by wkloucek** [comment]
Thanks a lot for this info! I'm gonna dig into that branch!

**Comment by wkloucek** [comment]
From my side we can close this ticket because the lua is configured on the ingress object itself (as of [release/1.2.0](https://github.com/ONLYOFFICE/Kubernetes-Docs-Shards/tree/release/v1.2.0) branch)
